let exNumber = 3
let exBigInt = 10n
let exString = "string"
let exBoolean = true
let exNull = null
let exUndefined = undefined
let exObject = Math
let exSymbol = Symbol("foo")
let exFunction = alert

alert(`exNumber is ${typeof exNumber}
exBigInt is ${typeof exBigInt}
exString is ${typeof exString}
exBoolean is ${typeof exBoolean}
exNull is ${typeof exNull}
exUndefined is ${typeof exUndefined}
exObject is ${typeof exObject}
exSymbol is ${typeof exSymbol}
exFunction is ${typeof exFunction}`)
